version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service1
      - service2

  service1:
    image: service1
    build: ./service1
    ports:
      - 7001:7001
    restart: unless-stopped
  service2:
    image: service2
    build: ./service2
    ports:
      - 7002:7002
    restart: unless-stopped
    