version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 1109:1109
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jaf_server
      

  jaf_server:
    image: jaf_server
    build: ./jaf_server
    restart: unless-stopped
    volumes:
      - /bsee_1109:/service1/names

volumes:
  bsee_1109:
    